"""Curation handlers for MDF v2.

Provides API endpoints for curators to review, approve, or reject submissions.
This replaces the Globus Automate weboption-based curation workflow.

Curation states:
- pending_curation: Awaiting curator review
- approved: Curator approved, ready for DOI/indexing
- rejected: Curator rejected with reason
- published: DOI minted and indexed

Endpoints:
- GET /curation/pending - List submissions awaiting curation
- GET /curation/{source_id} - Get submission details for curation
- POST /curation/{source_id}/approve - Approve a submission
- POST /curation/{source_id}/reject - Reject a submission
"""

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from v2.metadata import parse_metadata, to_datacite
from v2.store import get_store as get_submission_store


# Curators can be defined by user ID or group
CURATOR_USER_IDS = set(
    os.environ.get("CURATOR_USER_IDS", "").split(",")
) - {""}

CURATOR_GROUP_IDS = set(
    os.environ.get("CURATOR_GROUP_IDS", "").split(",")
) - {""}


def _is_curator(auth: Dict[str, Any]) -> bool:
    """Check if the authenticated user is a curator."""
    user_id = auth.get("user_id", "")

    if user_id in CURATOR_USER_IDS:
        return True

    group_info = auth.get("group_info", "{}")
    if isinstance(group_info, str):
        try:
            group_info = json.loads(group_info)
        except Exception:
            group_info = {}

    user_groups = set(group_info.keys()) if isinstance(group_info, dict) else set()
    if user_groups & CURATOR_GROUP_IDS:
        return True

    if os.environ.get("ALLOW_ALL_CURATORS", "").lower() in ("true", "1", "yes"):
        return True

    return False


def _extract_title(submission: Dict[str, Any]) -> str:
    """Extract title from submission metadata."""
    meta = parse_metadata(submission)
    return meta.title


def _mint_doi_for_submission(submission: Dict[str, Any]) -> Dict[str, Any]:
    """Mint a DOI for an approved submission."""
    from v2.datacite import get_datacite_client

    try:
        client = get_datacite_client()
        meta = parse_metadata(submission)
        source_id = submission.get("source_id", "unknown")

        # Build DataCite payload using to_datacite
        doi_payload = to_datacite(
            meta,
            doi="",  # will be generated by the client
            url=f"https://materialsdatafacility.org/detail/{source_id}",
            source_id=source_id,
            created_at=submission.get("created_at"),
            published_at=submission.get("published_at"),
        )

        # Extract the metadata the client expects
        attrs = doi_payload["data"]["attributes"]
        doi_metadata = {
            "titles": attrs.get("titles", []),
            "creators": attrs.get("creators", []),
            "publisher": attrs.get("publisher", "Materials Data Facility"),
            "publication_year": attrs.get("publicationYear", datetime.now().year),
        }
        if attrs.get("descriptions"):
            doi_metadata["descriptions"] = attrs["descriptions"]
        if attrs.get("subjects"):
            doi_metadata["subjects"] = attrs["subjects"]
        if attrs.get("rightsList"):
            doi_metadata["rightsList"] = attrs["rightsList"]
        if attrs.get("fundingReferences"):
            doi_metadata["fundingReferences"] = attrs["fundingReferences"]

        result = client.mint_doi(
            source_id=source_id,
            metadata=doi_metadata,
            publish=True,
        )

        client.close()
        return result

    except Exception as e:
        return {"success": False, "error": str(e)}
