name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - published

jobs:
  deploy-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Determine environment to release to
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "Setting FLOW_ENVIRONMENT for prerelease"
            echo "FLOW_ENVIRONMENT=test" >> $GITHUB_ENV
          else
            echo "Setting FLOW_ENVIRONMENT for prod release"
            echo "FLOW_ENVIRONMENT=prod" >> $GITHUB_ENV
          fi


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install globus-sdk==3.28.0 mdf_toolbox==0.6.0
          pip list

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Deploy
        env:
          API_CLIENT_ID: '${{ secrets.API_CLIENT_ID }}'
          API_CLIENT_SECRET: '${{ secrets.API_CLIENT_SECRET }}'
          SMTP_HOSTNAME: '${{ secrets.SMTP_HOSTNAME }}'
          SMTP_USER: '${{ secrets.SMTP_USER }}'
          SMTP_PASS: '${{ secrets.SMTP_PASS }}'
        run: |
          cd automate
          PYTHONPATH=../aws/ python deploy_mdf_flow.py ${{ env.FLOW_ENVIRONMENT }} ${{ env.RELEASE_VERSION }}
