name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ expand_ci_job ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Check out the schema repo to package up the JSON schemae with function
    - name: Checkout schema repo
      uses: actions/checkout@v2
      with:
        repository: materials-data-facility/data-schemas
        ref: automate
        path: schemas

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r aws/requirements.txt
        pip install boto3
        pip list
    - name: Check for vulnerabilities in libraries
      run: |
        pip install safety
        pip freeze | safety check

    - name: Test with pytest
      run: |
        pip install -r aws/requirements.txt
        pip install -r aws/tests/requirements-test.txt
        PYTHONPATH=aws python -m pytest aws/tests

    #credentials to connect to AWS
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        profile_name: default
        project_name: MDFConnect
        runtime: python3.7

    - name: Determine which instance of lambda function to update
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV

    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
